{% set name = "openlineage-python" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openlineage_python-{{ version }}.tar.gz
  sha256: bdd86728db0d3d9d18a04578bc4bfdb367075020593340ac8d27977e867a49d1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling >=1.17
    - pip
  run:
    - python >=3.8
    - attrs >=23.1
    - python-dateutil >=2.8.2
    - pyyaml >=5.4
    - requests >=2.31.0

test:
  imports:
    - openlineage.client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/OpenLineage/OpenLineage
  summary: OpenLineage Python Client
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
extra:
  recipe-maintainers:
    - rxm7706
