{% set name = "openlineage-python" %}
{% set version = "1.13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openlineage_python-{{ version }}.tar.gz
  sha256: 693da517fa05239383dbe903302655955c452b21d73ed8e53cebf09ef783650e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling >=1.17
    - pip
  run:
    - python >=3.8
    - attrs >=20.0
    - python-dateutil >=2.8.2
    - pyyaml >=5.4
    - requests >=2.20.0
    - packaging >=21.0

test:
  imports:
    - openlineage.client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/OpenLineage/OpenLineage
  summary: OpenLineage Python Client
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
extra:
  recipe-maintainers:
    - rxm7706
