{% set name = "openlineage-python" %}
{% set version = "1.28.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/openlineage_python-{{ version }}.tar.gz
  sha256: 064f2c463841cba8d158718f457c0f5b22758cda71721afd040e77b41f2844b1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.17
    - pip
  run:
    - python >={{ python_min }}
    - attrs >=20.0
    - python-dateutil >=2.8.2
    - pyyaml >=5.4
    - requests >=2.20.0
    - packaging >=21.0

test:
  imports:
    - openlineage.client
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/OpenLineage/OpenLineage
  summary: OpenLineage Python Client
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
extra:
  recipe-maintainers:
    - rxm7706
