# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: openlineage-python
  version: "1.39.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/openlineage_python-${{ version }}.tar.gz
  sha256: 1a32c349f60c3588d35bed03e7afddd907a434f31771d7b047b194e8e5edab09

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - ol-generate-code = openlineage.client.generator.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling >=1.17
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - attrs >=20.0
    - python-dateutil >=2.8.2
    - pyyaml >=5.4
    - requests >=2.32.4
    - httpx >=0.27.0
    - packaging >=21.0
    - python-build >=1.2.2

tests:
  - python:
      imports:
        - openlineage.client
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
        - ruff
        - click
        - datamodel-code-generator ==0.25.4
    script:
      - ol-generate-code --help

about:
  homepage: https://github.com/OpenLineage/OpenLineage
  summary: OpenLineage Python Client
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - millsks
