# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: openlineage-python
  version: "1.43.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/OpenLineage/OpenLineage/archive/refs/tags/${{ version }}.tar.gz
  sha256: 3cea76c502c86986667cbff3b5c90e181d7fde2376505215a5a8d88b70341d98

build:
  number: 0
  noarch: python
  script:
    - cd client/python
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - ol-generate-code = openlineage.client.generator.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - uv-build >=0.9.4,<0.10.0
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - attrs >=20.0
    - python-dateutil >=2.8.2
    - pyyaml >=5.4
    - requests >=2.32.4
    - httpx >=0.27.0
    - packaging >=21.0
    - python-build >=1.2.2

tests:
  - python:
      imports:
        - openlineage.client
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
        - ruff
        - click
        - datamodel-code-generator ==0.25.4
    script:
      - ol-generate-code --help

about:
  homepage: https://github.com/OpenLineage/OpenLineage
  summary: OpenLineage Python Client
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - millsks
    - xylar
